spring.application.name=energydashboard

spring.datasource.url=jdbc:postgresql://localhost:5432/energydashboard
spring.datasource.username=energydashboard
spring.datasource.password=energydashboard
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=MRUXLtUEZRWEe3_GUAp.2XUVfhvR7m.VMe3tQc8LPC7y@nQjyLZo9a8*XoqL
jwt.expiration=86400000